name: Validate for HACS

on:
  push:
  pull_request:

jobs:
  validate-hassfest:
    name: hassfest action
    runs-on: "ubuntu-latest"
    steps:
        - name: check out
          uses: "actions/checkout@v2"
        - name: hassfest validation
          uses: "home-assistant/actions/hassfest@master"
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
